name=Dostmann433
version=1.0.0
author=FandSonthesizer
maintainer=FandSonthesizer
sentence=Dostmann 433 MHz sender and receiver implementation.
paragraph=Supports TFA Dostmann 30.3227.02 protocol (payload, CRC, Manchester).
category=Communication
url=https://github.com/FandSonthesizer/433Mhz-30.3227.02-ReceiverAndSender
architectures=*